### ISSUE TITLE
Implement a method for generating request queries.

### ISSUE THREAD

**Issue by DraxCodes** [DraxCodes/NewsAPI.Net#2]
Currently the Request Query is generated by simply newing up a `NewsRequest`. The limitation of this is that the NewsRequest has the wrong properties for a Top Headlines api request. 

To fix that I am thinking there will be a method on the NewsClient that is named `GenerateRequest`. It would take a `RequestType` and return an instance of the correct NewsRequest model.

This would mean a rather big refactor of the current way we generate a request but most of it would be naming. Example end user implementation:

```cs
var request = newsClient.GenerateRequest(RequestType.TopHeadlines);
request.AddSource("Some Source Such as BBC");
request.SetCountry(Countries.Uk);
request.Filter("Some Filter Query such as .NetCore");

var result = newsClient.FetchNews(request);
```

**Comment by MarcusOtter** [comment]
I would be interested in doing this, but I don't really understand what you mean by "return an instance of the correct NewsRequest model". I looked at the API docs and it looks like the requests will have completely different properties as you said, so maybe it's worth making two different requests? Like `EverythingRequest` and `TopHeadlineRequest`.

Or maybe it could be even simpler, and the client would have `.FetchEverythingAsync()` or `.FetchTopHeadlinesAsync()`, taking the request as parameters? Just throwing ideas :smile:

**Comment by DraxCodes** [comment]
So I totally lost my train of thought for this issue. I had a good idea just can't remember what it was lol.

I think for simplicities sake having the two different methods is going to be the easier way to handle this for now. We could certainly have it take params for the request as you mentioned too.

If you would like to take this still, let me know and I will assign you to the issue :)

**Comment by MarcusOtter** [comment]
@DraxCodes Gotcha, yeah I'll have a look at this tomorrow morning :relaxed:
